project:
  type: website
  output-dir: docs

website:
  title: "MtG Kubbur"
  description: "Magic: The Gathering Cube Drafts á Íslandi"
  site-url: "https://mtgkubbur.is"

  navbar:
    search: false
    right:
      - icon: github
        href: https://github.com/mtgkubbur/mtgkubbur.github.io
        aria-label: GitHub

  page-footer:
    center: "© 2026 MtG Kubbur"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    toc: false

engine: knitr
