project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "MtG Kubbur"
  favicon: favicon.svg
  description: "Magic: The Gathering Cube Drafts á Íslandi"
  site-url: "https://mtgkubbur.is"

  navbar:
    search: false
    left:
      - text: "Stigatafla"
        href: index.qmd
      - text: "Leikmaður"
        href: throun.qmd
      - text: "Einvígi"
        href: einvigi.qmd
    right:
      - icon: github
        href: https://github.com/mtgkubbur/mtgkubbur.github.io
        aria-label: GitHub

  page-footer:
    center: "© 2026 MtG Kubbur"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    toc: false

engine: knitr
